### ISSUE TITLE
App crash on Oneplus 5 android 9

### ISSUE THREAD

**Issue by raminxxx** [doodz/Doods.Xam.MonitorMyServer#2]
I have a nas omv 5
When i try to add my info to app then press test me app will crash
![Screenshot_20200126-133812__01](https://user-images.githubusercontent.com/13236879/73133684-7ba9d100-4041-11ea-9bf8-54711091bfa1.jpg)

**Comment by doodz** [comment]
ok, you need to use login/password ssh.
Ensure you have activate ssh on OMV web interface.
![image](https://user-images.githubusercontent.com/2842910/73133892-47c5b000-402f-11ea-8c77-28f78bb626b5.png)

**Comment by raminxxx** [comment]
Thanks
I disabled SSH for safety. After test it with ssh enabled and use root login it worked! 
Can you add omv to it without ssh?
Support with sshand root not so good

**Comment by doodz** [comment]
Yes of course, actually it's a beta,for OMV I use RPC. I will check permission for that. In second time , i will implement http support.
